### ISSUE TITLE
Stack won't support GHCJS 8.0.1 on arch linux

### ISSUE THREAD

**Issue by cfraz89** [concurhaskell/concur-react-starter#1]
Hi,

When building the starter with stack, I got the following output:
`
Downloaded ghcjs-0.2.1.9007019_ghc-8.0.1.
Setting up GHCJS build environmentNo information found for ghc-8.0.1.
Supported versions for OS key 'linux64-tinfo6-nopie': GhcVersion 8.0.2, GhcVersion 8.2.1, GhcVersion 8.2.2
`

`
$ stack --version
Version 1.6.3, Git revision b27e629b8c4ce369e3b8273f04db193b060000db (5454 commits) x86_64 hpack-0.20.0
`

If I update the stack-ghcjs.yaml to use a newer untested build of ghcjs, everything is ok.

```
resolver: lts-9.13
packages:
- location: .
- location:
    git: https://github.com/ajnsit/concur
    commit: 06f8b226935bad2bfd4c6b8b6a76cfab730988aa
  extra-dep: true
  subdirs:
    - concur-core
    - concur-react
extra-deps:
- natural-transformation-0.4
flags: {}
extra-package-dbs: []

compiler: ghcjs-0.2.1.9009013_ghc-8.0.2
compiler-check: match-exact
setup-info:
  ghcjs:
    source:
      ghcjs-0.2.1.9009013_ghc-8.0.2:
           url: http://tolysz.org/ghcjs/untested/ghc-8.0-2017-11-15-lts-9.13-9009013.tar.gz
           sha1: c07cd955d86e78d4f72448d7039d1f1dfbb46685
```

**Comment by cfraz89** [comment]
Actually no good. With this ghcjs booting fails:

```
GHC/TopHandler.hs:88:29: error:
    Data constructor not in scope: STG_SIG_RST :: CInt
cabal: Error: some packages failed to install:
base-4.9.1.0-DUroNgAKIGQCIqmcCr1i33 failed during the building phase. The
exception was:
ExitFailure 1
primitive-0.6.2.0-CrQJFOPTQVY76A6o8V1CkN depends on primitive-0.6.2.0 which
failed to install.
transformers-0.5.2.0-IGRvs8mRrJ09Lm6BZ7wb9k depends on transformers-0.5.2.0
which failed to install.
```

**Comment by ajnsit** [comment]
Thanks for the bug report! This seems to be an issue with stack/ghcjs itself on Arch Linux. I don't have a quick solution since I don't use Arch myself, however I'll look into it and get back to you.

**Comment by cfraz89** [comment]
Ok got it going with the is stack-ghcs.yaml:

```
resolver: lts-8.11
packages:
- location: .
- location:
    git: https://github.com/ajnsit/concur
    commit: 06f8b226935bad2bfd4c6b8b6a76cfab730988aa
  extra-dep: true
  subdirs:
    - concur-core
    - concur-react
extra-deps:
- natural-transformation-0.4
flags: {}
extra-package-dbs: []

compiler: ghcjs-0.2.1.9008011_ghc-8.0.2
compiler-check: match-exact
setup-info:
  ghcjs:
    source:
      ghcjs-0.2.1.9008011_ghc-8.0.2:
           url: https://github.com/matchwood/ghcjs-stack-dist/raw/master/ghcjs-0.2.1.9008011.tar.gz
           sha1: a72a5181124baf64bcd0e68a8726e65914473b3b
```

It's this ghcjs build: https://github.com/matchwood/ghcjs-stack-dist
Not official, but it works.
